plugins {
    id 'com.android.library'
}

repositories {
    google()
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

android {
    namespace 'com.tfg.usbserial'
    compileSdk 33

    defaultConfig {
        minSdk 29  // Quest 2/3 usan Android 10+
        targetSdk 33
        
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // Librería USB Serial para Android
    implementation 'com.github.mik3y:usb-serial-for-android:3.7.0'
}
